// Generated by CoffeeScript 2.7.0
(function() {
  var $, addFile, addFiles, addImageItem, allowedImageExt, applyAll, applyWatermark, autoRefresh, canvasToBlob, clearAll, countEl, dataURItoBlob, downloadAll, downloadBlob, downloadOne, formatTimestamp, getOptions, graph, imageInput, input, inputItems, isSupportedImageFile, items, loadImageFromFile, makeItemName, makeStyle, pad2, readAsDataURL, refresh, sanitizeBaseName, stripExt, updateActions;

  $ = function(sel) {
    return document.querySelector(sel);
  };

  allowedImageExt = /\.(png|jpe?g|gif|webp|bmp)$/i;

  inputItems = ['text', 'color', 'alpha', 'angle', 'space', 'size'];

  input = {};

  imageInput = $('#image');

  graph = $('#graph');

  refresh = $('#refresh');

  autoRefresh = $('#auto-refresh');

  downloadAll = $('#download-all');

  clearAll = $('#clear-all');

  countEl = $('#count');

  items = [];

  pad2 = function(n) {
    if (n < 10) {
      return '0' + n;
    } else {
      return '' + n;
    }
  };

  formatTimestamp = function() {
    var d;
    d = new Date();
    return '' + d.getFullYear() + '-' + (pad2(d.getMonth() + 1)) + '-' + (pad2(d.getDate())) + ' ' + (pad2(d.getHours())) + (pad2(d.getMinutes())) + (pad2(d.getSeconds()));
  };

  stripExt = function(name) {
    if (name == null) {
      return '';
    }
    return name.replace(/\.[^\/.]+$/, '');
  };

  sanitizeBaseName = function(name) {
    return (name || '').replace(/[\\\/:*?"<>|]/g, '-').trim();
  };

  isSupportedImageFile = function(file) {
    if (file == null) {
      return false;
    }
    if ((file.type != null) && file.type.indexOf('image/') === 0) {
      return true;
    }
    if (allowedImageExt.test(file.name || '')) {
      return true;
    }
    return false;
  };

  dataURItoBlob = function(dataURI) {
    var arr, binStr, i, k, len, ref;
    binStr = atob((dataURI.split(','))[1]);
    len = binStr.length;
    arr = new Uint8Array(len);
    for (i = k = 0, ref = len - 1; (0 <= ref ? k <= ref : k >= ref); i = 0 <= ref ? ++k : --k) {
      arr[i] = binStr.charCodeAt(i);
    }
    return new Blob([arr], {
      type: 'image/png'
    });
  };

  canvasToBlob = function(canvas) {
    return new Promise(function(resolve, reject) {
      var err;
      if ((canvas != null ? canvas.toBlob : void 0) != null) {
        return canvas.toBlob((function(blob) {
          if (blob != null) {
            return resolve(blob);
          } else {
            return reject(new Error('toBlob failed'));
          }
        }), 'image/png');
      } else {
        try {
          return resolve(dataURItoBlob(canvas.toDataURL('image/png')));
        } catch (error) {
          err = error;
          return reject(err);
        }
      }
    });
  };

  downloadBlob = function(blob, filename) {
    var link, url;
    url = URL.createObjectURL(blob);
    link = document.createElement('a');
    link.download = filename;
    link.href = url;
    document.body.appendChild(link);
    link.click();
    return setTimeout(function() {
      URL.revokeObjectURL(url);
      return document.body.removeChild(link);
    }, 1000);
  };

  readAsDataURL = function(file) {
    return new Promise(function(resolve, reject) {
      var fileReader;
      fileReader = new FileReader();
      fileReader.onload = function() {
        return resolve(fileReader.result);
      };
      fileReader.onerror = function() {
        return reject(fileReader.error || new Error('FileReader error'));
      };
      return fileReader.readAsDataURL(file);
    });
  };

  loadImageFromFile = function(file) {
    return readAsDataURL(file).then(function(dataURL) {
      return new Promise(function(resolve, reject) {
        var img;
        img = new Image();
        img.onload = function() {
          return resolve(img);
        };
        img.onerror = function() {
          return reject(new Error('图片加载失败'));
        };
        return img.src = dataURL;
      });
    });
  };

  getOptions = function() {
    return {
      text: (input.text.value || '').trim(),
      color: input.color.value,
      alpha: parseFloat(input.alpha.value),
      angle: parseFloat(input.angle.value),
      space: parseFloat(input.space.value),
      size: parseFloat(input.size.value)
    };
  };

  makeStyle = function(color, alpha) {
    var match;
    match = (color || '').match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);
    if (match == null) {
      return 'rgba(0,0,0,' + alpha + ')';
    }
    return 'rgba(' + (parseInt(match[1], 16)) + ',' + (parseInt(match[2], 16)) + ',' + (parseInt(match[3], 16)) + ',' + alpha + ')';
  };

  applyWatermark = function(item, options) {
    var canvas, ctx, i, j, k, l, margin, ref, ref1, ref2, ref3, step, textSize, width, x, y;
    if ((item != null ? item.canvas : void 0) == null) {
      return;
    }
    item.redraw();
    if (!options.text) {
      return;
    }
    canvas = item.canvas;
    ctx = item.ctx;
    textSize = options.size * Math.max(15, (Math.min(canvas.width, canvas.height)) / 25);
    ctx.save();
    ctx.translate(canvas.width / 2, canvas.height / 2);
    ctx.rotate(options.angle * Math.PI / 180);
    ctx.fillStyle = makeStyle(options.color, options.alpha);
    ctx.font = 'bold ' + textSize + 'px -apple-system,"Helvetica Neue",Helvetica,Arial,"PingFang SC","Hiragino Sans GB","WenQuanYi Micro Hei",sans-serif';
    width = (ctx.measureText(options.text)).width;
    step = Math.sqrt((Math.pow(canvas.width, 2)) + (Math.pow(canvas.height, 2)));
    margin = (ctx.measureText('啊')).width;
    x = Math.ceil(step / (width + margin));
    y = Math.ceil((step / (options.space * textSize)) / 2);
    for (i = k = ref = -x, ref1 = x; (ref <= ref1 ? k <= ref1 : k >= ref1); i = ref <= ref1 ? ++k : --k) {
      for (j = l = ref2 = -y, ref3 = y; (ref2 <= ref3 ? l <= ref3 : l >= ref3); j = ref2 <= ref3 ? ++l : --l) {
        ctx.fillText(options.text, (width + margin) * i, options.space * textSize * j);
      }
    }
    ctx.restore();
  };

  applyAll = function() {
    var options;
    options = getOptions();
    return items.forEach(function(item) {
      return applyWatermark(item, options);
    });
  };

  updateActions = function() {
    if (countEl != null) {
      if (items.length > 0) {
        countEl.textContent = '已添加 ' + items.length + ' 张图片';
      } else {
        countEl.textContent = '';
      }
    }
    if (downloadAll != null) {
      if (items.length > 0) {
        downloadAll.removeAttribute('disabled');
      } else {
        downloadAll.setAttribute('disabled', 'disabled');
      }
    }
    if (clearAll != null) {
      if (items.length > 0) {
        return clearAll.removeAttribute('disabled');
      } else {
        return clearAll.setAttribute('disabled', 'disabled');
      }
    }
  };

  makeItemName = function(file, fallbackBase) {
    var base;
    base = sanitizeBaseName(stripExt(file != null ? file.name : void 0) || fallbackBase || 'image');
    return base;
  };

  addImageItem = function(img, meta = {}) {
    var canvas, ctx, item, nameEl, redraw, wrapper;
    canvas = document.createElement('canvas');
    canvas.width = img.width;
    canvas.height = img.height;
    ctx = canvas.getContext('2d');
    ctx.drawImage(img, 0, 0);
    redraw = function() {
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      return ctx.drawImage(img, 0, 0);
    };
    item = {
      id: '' + Date.now() + '-' + Math.random().toString(16).slice(2),
      img: img,
      canvas: canvas,
      ctx: ctx,
      redraw: redraw,
      baseName: meta.baseName,
      displayName: meta.displayName
    };
    wrapper = document.createElement('div');
    wrapper.className = 'img-item';
    nameEl = document.createElement('div');
    nameEl.className = 'img-name';
    nameEl.textContent = item.displayName || item.baseName || '图片';
    wrapper.appendChild(nameEl);
    wrapper.appendChild(canvas);
    graph.appendChild(wrapper);
    canvas.addEventListener('click', function() {
      return downloadOne(item);
    });
    items.push(item);
    updateActions();
    applyWatermark(item, getOptions());
  };

  downloadOne = function(item, batchStamp = null, index = null) {
    var base, filename, stamp, suffix;
    stamp = batchStamp || formatTimestamp();
    base = item.baseName || 'image';
    suffix = index != null ? '-' + (index + 1) : '';
    filename = base + suffix + '-' + stamp + '.png';
    return canvasToBlob(item.canvas).then(function(blob) {
      return downloadBlob(blob, filename);
    }).catch(function(err) {
      console.error(err);
      return alert('导出失败，请重试');
    });
  };

  addFile = function(file, meta = {}) {
    if (!isSupportedImageFile(file)) {
      return;
    }
    return loadImageFromFile(file).then(function(img) {
      var baseName, displayName;
      baseName = meta.baseName || makeItemName(file, 'clipboard');
      displayName = meta.displayName || (file.name || baseName);
      return addImageItem(img, {
        baseName: baseName,
        displayName: displayName
      });
    }).catch(function(err) {
      console.error(err);
      return alert('读取图片失败');
    });
  };

  addFiles = function(files) {
    return Array.from(files || []).forEach(function(file) {
      if (isSupportedImageFile(file)) {
        return addFile(file);
      } else {
        return alert('仅支持图片文件（png/jpg/gif/webp/bmp 等）');
      }
    });
  };

  if (imageInput != null) {
    imageInput.addEventListener('change', function() {
      addFiles(this.files);
      return this.value = '';
    });
  }

  document.addEventListener('paste', function(e) {
    var baseName, data, displayName, f, idx, it, k, l, len1, len2, pasted, ref, ref1, results, stamp;
    data = e.clipboardData;
    if (!(data != null ? (ref = data.items) != null ? ref.length : void 0 : void 0)) {
      return;
    }
    pasted = [];
    ref1 = data.items;
    for (k = 0, len1 = ref1.length; k < len1; k++) {
      it = ref1[k];
      if (!(it.kind === 'file')) {
        continue;
      }
      f = it.getAsFile();
      if (f != null) {
        pasted.push(f);
      }
    }
    if (pasted.length === 0) {
      return;
    }
    stamp = formatTimestamp();
    results = [];
    for (idx = l = 0, len2 = pasted.length; l < len2; idx = ++l) {
      f = pasted[idx];
      baseName = 'clipboard';
      displayName = '剪贴板-' + stamp + '-' + (idx + 1);
      results.push(addFile(f, {
        baseName: baseName,
        displayName: displayName
      }));
    }
    return results;
  });

  if (autoRefresh != null) {
    autoRefresh.addEventListener('change', function() {
      if (this.checked) {
        return refresh.setAttribute('disabled', 'disabled');
      } else {
        return refresh.removeAttribute('disabled');
      }
    });
  }

  inputItems.forEach(function(item) {
    var el;
    el = $('#' + item);
    input[item] = el;
    return el.addEventListener('input', function() {
      if (autoRefresh.checked) {
        return applyAll();
      }
    });
  });

  if (refresh != null) {
    refresh.addEventListener('click', applyAll);
  }

  if (downloadAll != null) {
    downloadAll.addEventListener('click', function() {
      var downloadNext, stamp;
      if (items.length === 0) {
        return;
      }
      stamp = formatTimestamp();
      downloadNext = function(idx) {
        if (idx >= items.length) {
          return;
        }
        return downloadOne(items[idx], stamp, idx).then((function() {
          return setTimeout((function() {
            return downloadNext(idx + 1);
          }), 200);
        }).catch((function() {
          return setTimeout((function() {
            return downloadNext(idx + 1);
          }), 200);
        })));
      };
      return downloadNext(0);
    });
  }

  if (clearAll != null) {
    clearAll.addEventListener('click', function() {
      items.length = 0;
      graph.innerHTML = '';
      return updateActions();
    });
  }

  updateActions();

}).call(this);
